# Generated by Django 5.0.6 on 2024-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=200)),
                ('responsibility', models.CharField(max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='team_image')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AWS Team',
                'verbose_name_plural': 'AWS Teams',
            },
        ),
    ]
