# Generated by Django 5.0.6 on 2024-07-23 16:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Event title')),
                ('description', models.TextField(help_text='Event Description')),
                ('venue', models.TextField(help_text='Event venue')),
                ('collaboration_with', models.TextField(help_text='Collaborated by')),
                ('guest_speaker', models.TextField()),
                ('image', models.ImageField(help_text='Event poster', upload_to='events_poster')),
                ('startDate', models.DateTimeField(help_text='Event start time')),
                ('endDate', models.DateTimeField(help_text='Event end time')),
                ('facilitator', models.TextField(help_text='Event facilitator')),
                ('detail', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('EventStatus', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], help_text='Select the current status of the event.', max_length=20)),
            ],
            options={
                'verbose_name': 'AWS Event',
                'verbose_name_plural': 'AWS Events',
            },
        ),
        migrations.CreateModel(
            name='GuestSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpeakerName', models.CharField(max_length=100)),
                ('SpeakerTitle', models.CharField(max_length=100)),
                ('SpeakerBio', models.TextField()),
                ('SpeakerPhoto', models.ImageField(blank=True, null=True, upload_to='speaker_photos')),
            ],
            options={
                'verbose_name': 'AWS Guest Speaker',
                'verbose_name_plural': 'AWS Guest Speakers',
            },
        ),
        migrations.CreateModel(
            name='GrandEventSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Event title')),
                ('description', models.TextField(help_text='Event Description')),
                ('venue', models.TextField(help_text='Event venue')),
                ('collaboration_with', models.TextField(help_text='Collaborated by')),
                ('image', models.ImageField(help_text='Event poster', upload_to='events_poster')),
                ('startDate', models.DateTimeField(help_text='Event start time')),
                ('endDate', models.DateTimeField(help_text='Event end time')),
                ('facilitator', models.TextField(help_text='Event facilitator')),
                ('detail', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('EventStatus', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], help_text='Select the current status of the event.', max_length=20)),
                ('guest_speakers', models.ManyToManyField(help_text='Guest speaker for the event', related_name='events', to='event.guestspeaker')),
            ],
            options={
                'verbose_name': 'AWS Grand Event',
                'verbose_name_plural': 'AWS Grand Events',
            },
        ),
    ]
