# Generated by Django 5.0.6 on 2024-07-24 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_suscriber', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_suscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_suscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventsystem')),
            ],
        ),
    ]
