# Generated by Django 5.0.6 on 2024-07-24 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event_suscribed', 'account_suscriber'), ('event_suscribed', 'participant_suscriber')},
        ),
    ]
