# Generated by Django 5.0.6 on 2024-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventparticipant_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200)),
                ('merchant_logo', models.ImageField(upload_to='merchant_sponsers')),
                ('merchant_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grandeventsystem',
            name='description',
            field=models.TextField(help_text='Event Description', max_length=800),
        ),
        migrations.AlterField(
            model_name='grandeventsystem',
            name='facilitator',
            field=models.CharField(help_text='Event facilitator', max_length=400),
        ),
        migrations.AlterField(
            model_name='grandeventsystem',
            name='title',
            field=models.CharField(help_text='Event title', max_length=400),
        ),
        migrations.AlterField(
            model_name='grandeventsystem',
            name='venue',
            field=models.CharField(help_text='Event venue', max_length=200),
        ),
        migrations.AddField(
            model_name='grandeventsystem',
            name='event_sponsers',
            field=models.ManyToManyField(help_text='Sponsers for the event', to='event.merchantsponsers'),
        ),
    ]
