# Generated by Django 5.0.6 on 2024-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_merchantsponsers_alter_grandeventsystem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantsponsers',
            options={'verbose_name': 'Merchant Sponser', 'verbose_name_plural': 'Merchant Sponsers'},
        ),
        migrations.AddField(
            model_name='guestspeaker',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestspeaker',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestspeaker',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
