# Generated by Django 5.0.6 on 2024-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_grandeventsystem_eventstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandEventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='grandeventsession')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startTime', models.TimeField(help_text='Session start time')),
                ('endTime', models.TimeField(help_text='Session end time')),
            ],
        ),
    ]
