# Generated by Django 5.0.6 on 2024-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_grandeventsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandeventsystem',
            name='session',
            field=models.ManyToManyField(help_text='All Sessions in the event', related_name='sessions', to='event.grandeventsession'),
        ),
        migrations.AlterField(
            model_name='grandeventsystem',
            name='event_sponsers',
            field=models.ManyToManyField(help_text='Sponsers for the event', related_name='sponsers', to='event.merchantsponsers'),
        ),
    ]
