# Generated by Django 5.0.6 on 2024-07-27 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_grandeventsystem_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_suscriber', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_suscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_suscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.grandeventsystem')),
            ],
            options={
                'unique_together': {('event_suscribed', 'account_suscriber'), ('event_suscribed', 'participant_suscriber')},
            },
        ),
    ]
